// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATfcTaoNMulJ0veA5LBrEaoguUqelKhgI',
    appId: '1:190051312370:web:24c770672ed4b22d8f266b',
    messagingSenderId: '190051312370',
    projectId: 'clockon-1b77b',
    authDomain: 'clockon-1b77b.firebaseapp.com',
    storageBucket: 'clockon-1b77b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbxfMMHalGcAk2iHWfWi59mgye0GRAa7w',
    appId: '1:190051312370:android:e4d69373570785d18f266b',
    messagingSenderId: '190051312370',
    projectId: 'clockon-1b77b',
    storageBucket: 'clockon-1b77b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgA4bGhhhzLX5gXv1ElzxTEwLlEMxz0IQ',
    appId: '1:190051312370:ios:4952efceb4eb6ce48f266b',
    messagingSenderId: '190051312370',
    projectId: 'clockon-1b77b',
    storageBucket: 'clockon-1b77b.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiClockon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgA4bGhhhzLX5gXv1ElzxTEwLlEMxz0IQ',
    appId: '1:190051312370:ios:4952efceb4eb6ce48f266b',
    messagingSenderId: '190051312370',
    projectId: 'clockon-1b77b',
    storageBucket: 'clockon-1b77b.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiClockon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATfcTaoNMulJ0veA5LBrEaoguUqelKhgI',
    appId: '1:190051312370:web:421621ac9fbfda2a8f266b',
    messagingSenderId: '190051312370',
    projectId: 'clockon-1b77b',
    authDomain: 'clockon-1b77b.firebaseapp.com',
    storageBucket: 'clockon-1b77b.firebasestorage.app',
  );
}
